# encoding: utf-8

# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.register.com/rcomexpress_status_registered.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/record/parser/whois.register.com.rb'

describe Whois::Record::Parser::WhoisRegisterCom, "rcomexpress_status_registered.expected" do

  before(:each) do
    file = fixture("responses", "whois.register.com/rcomexpress_status_registered.txt")
    part = Whois::Record::Part.new(:body => File.read(file))
    @parser = klass.new(part)
  end

  describe "#status" do
    it do
      lambda { @parser.status }.should raise_error(Whois::PropertyNotSupported)
    end
  end
  describe "#available?" do
    it do
      @parser.available?.should == false
    end
  end
  describe "#registered?" do
    it do
      @parser.registered?.should == true
    end
  end
  describe "#created_on" do
    it do
      @parser.created_on.should be_a(Time)
      @parser.created_on.should == Time.parse("11 Jan 2007 16:53:14")
    end
  end
  describe "#expires_on" do
    it do
      @parser.expires_on.should be_a(Time)
      @parser.expires_on.should == Time.parse("11 Jan 2013 16:53:00")
    end
  end
  describe "#registrant_contacts" do
    it do
      @parser.registrant_contacts.should be_a(Array)
      @parser.registrant_contacts.should have(1).items
      @parser.registrant_contacts[0].should be_a(Whois::Record::Contact)
      @parser.registrant_contacts[0].type.should         == Whois::Record::Contact::TYPE_REGISTRANT
      @parser.registrant_contacts[0].name.should         == "Joshua Baer"
      @parser.registrant_contacts[0].organization.should == "OtherInbox"
      @parser.registrant_contacts[0].address.should      == "PMB 520, 3267 Bee Cave #107"
      @parser.registrant_contacts[0].city.should         == "Austin"
      @parser.registrant_contacts[0].zip.should          == "78746"
      @parser.registrant_contacts[0].state.should        == "TX"
      @parser.registrant_contacts[0].country.should      == "US"
      @parser.registrant_contacts[0].phone.should        == nil
      @parser.registrant_contacts[0].fax.should          == nil
      @parser.registrant_contacts[0].email.should        == nil
    end
  end
  describe "#admin_contacts" do
    it do
      @parser.admin_contacts.should be_a(Array)
      @parser.admin_contacts.should have(1).items
      @parser.admin_contacts[0].should be_a(Whois::Record::Contact)
      @parser.admin_contacts[0].type.should         == Whois::Record::Contact::TYPE_ADMIN
      @parser.admin_contacts[0].name.should         == "Joshua Baer"
      @parser.admin_contacts[0].organization.should == nil
      @parser.admin_contacts[0].address.should      == "PMB 520, 3267 Bee Cave #107"
      @parser.admin_contacts[0].city.should         == "Austin"
      @parser.admin_contacts[0].zip.should          == "78746"
      @parser.admin_contacts[0].state.should        == "TX"
      @parser.admin_contacts[0].country.should      == "US"
      @parser.admin_contacts[0].phone.should        == "+1.5126921881"
      @parser.admin_contacts[0].fax.should          == nil
      @parser.admin_contacts[0].email.should        == "dns@joshuabaer.com"
    end
  end
  describe "#technical_contacts" do
    it do
      @parser.technical_contacts.should be_a(Array)
      @parser.technical_contacts.should have(1).items
      @parser.technical_contacts[0].should be_a(Whois::Record::Contact)
      @parser.technical_contacts[0].type.should         == Whois::Record::Contact::TYPE_TECHNICAL
      @parser.technical_contacts[0].name.should         == "Joshua Baer"
      @parser.technical_contacts[0].organization.should == nil
      @parser.technical_contacts[0].address.should      == "PMB 520, 3267 Bee Cave #107"
      @parser.technical_contacts[0].city.should         == "Austin"
      @parser.technical_contacts[0].zip.should          == "78746"
      @parser.technical_contacts[0].state.should        == "TX"
      @parser.technical_contacts[0].country.should      == "US"
      @parser.technical_contacts[0].phone.should        == "+1.5126921881"
      @parser.technical_contacts[0].fax.should          == nil
      @parser.technical_contacts[0].email.should        == "dns@joshuabaer.com"
    end
  end
  describe "#nameservers" do
    it do
      @parser.nameservers.should be_a(Array)
      @parser.nameservers.should have(5).items
      @parser.nameservers[0].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[0].name.should == "a.ns.zerigo.net"
      @parser.nameservers[1].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[1].name.should == "b.ns.zerigo.net"
      @parser.nameservers[2].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[2].name.should == "c.ns.zerigo.net"
      @parser.nameservers[3].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[3].name.should == "d.ns.zerigo.net"
      @parser.nameservers[4].should be_a(Whois::Record::Nameserver)
      @parser.nameservers[4].name.should == "e.ns.zerigo.net"
    end
  end
end
